apiVersion: batch/v1
kind: Job
metadata:
  name: eventclassify
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - name: mycontainer-extehrmanntraut
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/extehrmanntraut/german_nlp_training-uhhlt_event_classification:latest
          imagePullPolicy: "Always"
          env:
            - name: MODEL
              value: "deepset/gbert-base"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "2"
              memory: "8Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "2"
              memory: "8Gi"
          volumeMounts:
            - mountPath: /.cache
              name: cache
            - mountPath: /outputs # directory IN the container
              name: outputs # matches volume-name from below
      nodeName: gwerlum 
      #affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #          nodeSelectorTerms:
      #            - matchExpressions:
      #              - key: gputype
      #                operator: In
      #                values:
      #                - rtx8000
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: outputs
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: extehrmanntraut  # <namespace>
            path: "/home/ext/ehrmanntraut/german_nlp_training/outputs/uhh-lt_event-classification/" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
        - name: cache
          emptyDir:
            sizeLimit: 4Gi

