apiVersion: batch/v1
kind: Job
metadata:
  name: flairflert
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-low
      containers:
        - name: mycontainer-extehrmanntraut
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/extehrmanntraut/german_nlp_training/flair_flert:latest
          imagePullPolicy: "Always"
          env:
            - name: MODEL
              value: "deepset/gbert-large"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "1"
              memory: "8Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "1"
              memory: "8Gi"
          volumeMounts:
            - mountPath: /output # directory IN the container
              name: outputs # matches volume-name from below
      nodeSelector:
        gputype: "a100"
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: outputs
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: extehrmanntraut  # <namespace>
            path: "/home/ext/ehrmanntraut/german_nlp_training/outputs/flair_flert" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret

