apiVersion: batch/v1
kind: Job
metadata:
  name: germannlptraining-redewiedergabe
spec:
  backoffLimit: 0
  template:
    spec:
      priorityClassName: research-med
      containers:
        - name: mycontainer-extehrmanntraut
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/extehrmanntraut/german_nlp_training/redewiedergabe:latest
          imagePullPolicy: "Always"
          env:
            - name: MODEL
              value: "/model_store/gbert_large_literary"
            - name: SEGMENT_LENGTH
              value: "300"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "32Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "16Gi"
          volumeMounts:
            - mountPath: /output # directory IN the container
              name: outputs # matches volume-name from below
            - mountPath: /model_store # directory IN the container
              name: modelstore  # matches volume-name from below
      #nodeName: gwerlum 
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: outputs
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: extehrmanntraut  # <namespace>
            path: "/home/ext/ehrmanntraut/german_nlp_training/outputs/redewiedergabe/" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
        - name: modelstore 
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: extehrmanntraut  # <namespace>
            path: "/home/ext/ehrmanntraut/german_nlp_training/model_store/" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret

